require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LimitedEditionsController do

  # This should return the minimal set of attributes required to create a valid
  # LimitedEdition. As you add validations to LimitedEdition, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LimitedEditionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all limited_editions as @limited_editions" do
      limited_edition = LimitedEdition.create! valid_attributes
      get :index, {}, valid_session
      assigns(:limited_editions).should eq([limited_edition])
    end
  end

  describe "GET show" do
    it "assigns the requested limited_edition as @limited_edition" do
      limited_edition = LimitedEdition.create! valid_attributes
      get :show, {:id => limited_edition.to_param}, valid_session
      assigns(:limited_edition).should eq(limited_edition)
    end
  end

  describe "GET new" do
    it "assigns a new limited_edition as @limited_edition" do
      get :new, {}, valid_session
      assigns(:limited_edition).should be_a_new(LimitedEdition)
    end
  end

  describe "GET edit" do
    it "assigns the requested limited_edition as @limited_edition" do
      limited_edition = LimitedEdition.create! valid_attributes
      get :edit, {:id => limited_edition.to_param}, valid_session
      assigns(:limited_edition).should eq(limited_edition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LimitedEdition" do
        expect {
          post :create, {:limited_edition => valid_attributes}, valid_session
        }.to change(LimitedEdition, :count).by(1)
      end

      it "assigns a newly created limited_edition as @limited_edition" do
        post :create, {:limited_edition => valid_attributes}, valid_session
        assigns(:limited_edition).should be_a(LimitedEdition)
        assigns(:limited_edition).should be_persisted
      end

      it "redirects to the created limited_edition" do
        post :create, {:limited_edition => valid_attributes}, valid_session
        response.should redirect_to(LimitedEdition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved limited_edition as @limited_edition" do
        # Trigger the behavior that occurs when invalid params are submitted
        LimitedEdition.any_instance.stub(:save).and_return(false)
        post :create, {:limited_edition => {}}, valid_session
        assigns(:limited_edition).should be_a_new(LimitedEdition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LimitedEdition.any_instance.stub(:save).and_return(false)
        post :create, {:limited_edition => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested limited_edition" do
        limited_edition = LimitedEdition.create! valid_attributes
        # Assuming there are no other limited_editions in the database, this
        # specifies that the LimitedEdition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LimitedEdition.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => limited_edition.to_param, :limited_edition => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested limited_edition as @limited_edition" do
        limited_edition = LimitedEdition.create! valid_attributes
        put :update, {:id => limited_edition.to_param, :limited_edition => valid_attributes}, valid_session
        assigns(:limited_edition).should eq(limited_edition)
      end

      it "redirects to the limited_edition" do
        limited_edition = LimitedEdition.create! valid_attributes
        put :update, {:id => limited_edition.to_param, :limited_edition => valid_attributes}, valid_session
        response.should redirect_to(limited_edition)
      end
    end

    describe "with invalid params" do
      it "assigns the limited_edition as @limited_edition" do
        limited_edition = LimitedEdition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LimitedEdition.any_instance.stub(:save).and_return(false)
        put :update, {:id => limited_edition.to_param, :limited_edition => {}}, valid_session
        assigns(:limited_edition).should eq(limited_edition)
      end

      it "re-renders the 'edit' template" do
        limited_edition = LimitedEdition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LimitedEdition.any_instance.stub(:save).and_return(false)
        put :update, {:id => limited_edition.to_param, :limited_edition => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested limited_edition" do
      limited_edition = LimitedEdition.create! valid_attributes
      expect {
        delete :destroy, {:id => limited_edition.to_param}, valid_session
      }.to change(LimitedEdition, :count).by(-1)
    end

    it "redirects to the limited_editions list" do
      limited_edition = LimitedEdition.create! valid_attributes
      delete :destroy, {:id => limited_edition.to_param}, valid_session
      response.should redirect_to(limited_editions_url)
    end
  end

end
